name: Deploy Blazor WASM to GitHub Pages

env:
  PUBLISH_DIR: src/Client/bin/Release/net6.0/publish/wwwroot

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish application
      run: dotnet publish -c Release
    
    # Rewrite the base href so that resources like CSS and scripts can load properly.
    - name: Rewrite base href
      if: success()
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /SnakeEyes/ # Make sure this matches your repo name
        
    # Add .nojekyll file to ensure GitHub Pages doesn't treat this as a Jekyll project
    - name: Add .nojekyll file
      run: touch ${{ env.PUBLISH_DIR }}/.nojekyll

    - name: Commit to GitHub Pages Repo
      if: success()
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
